# Generated by Django 2.1.7 on 2019-05-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='tags',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='tags',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
