# Generated by Django 2.1.4 on 2018-12-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
