# Generated by Django 2.1.7 on 2019-05-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20190508_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='tags',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='tags',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
