# Generated by Django 2.1.7 on 2019-05-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_auto_20190518_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='tags',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='tags',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
