# Generated by Django 2.1.2 on 2018-12-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_auto_20181207_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
