# Generated by Django 2.1.1 on 2018-10-05 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181004_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentAuthorName', to=settings.AUTH_USER_MODEL),
        ),
    ]
