# Generated by Django 2.1.2 on 2018-11-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181116_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
