# Generated by Django 2.1.1 on 2018-10-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181004_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='body',
            new_name='html',
        ),
    ]
