# Generated by Django 2.1.2 on 2018-11-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articlecomment_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-last_modified',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'ordering': ('-last_modified',), 'verbose_name': 'Article Comment', 'verbose_name_plural': 'Article Comments'},
        ),
        migrations.RenameField(
            model_name='articlecomment',
            old_name='article',
            new_name='document_id',
        ),
    ]
