# Generated by Django 2.1.2 on 2018-11-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articlelikes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlelikes',
            options={'ordering': ('-date_created',), 'verbose_name': 'Article Like', 'verbose_name_plural': 'Articles Likes'},
        ),
        migrations.RemoveField(
            model_name='articlelikes',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='articlelikes',
            name='last_modified_by',
        ),
    ]
