# Generated by Django 2.1.7 on 2019-05-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='tags',
            field=models.CharField(default='Newsletter', max_length=512),
        ),
    ]
