# Generated by Django 2.1.1 on 2018-10-14 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_newsletter_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='date_modified',
        ),
    ]
