# Generated by Django 2.1.2 on 2018-11-18 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletters', '0005_auto_20181117_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='newsletters.Newsletter')),
            ],
            options={
                'verbose_name': 'Newsletter Like',
                'verbose_name_plural': 'Newsletters Likes',
                'ordering': ('-date_created',),
            },
        ),
        migrations.AlterField(
            model_name='newslettercomment',
            name='document_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='newsletters.Newsletter'),
        ),
    ]
