# Generated by Django 2.1.2 on 2018-11-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0009_auto_20181117_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='tags',
            field=models.CharField(default='Newsletter', max_length=128),
        ),
        migrations.AlterField(
            model_name='newslettercomment',
            name='document_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='newsletters.Newsletter'),
        ),
        migrations.AlterField(
            model_name='newsletterlikes',
            name='document_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='newsletters.Newsletter'),
        ),
    ]
