# Generated by Django 2.1.1 on 2018-09-22 00:11

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('title_description', models.TextField(blank=True, null=True)),
                ('title_btn', models.CharField(default='Join', max_length=50)),
                ('title_btn_url', models.CharField(blank=True, max_length=50, null=True)),
                ('jumbotron_text_color', models.CharField(default='#000000', max_length=7, validators=[pages.models.layout_validator])),
                ('jumbotron_bg_color', models.CharField(default='#eeeeee', max_length=7, validators=[pages.models.layout_validator])),
                ('content', models.TextField(blank=True, null=True)),
                ('show_nav', models.BooleanField(default=True, help_text='Show Navigation Bar?')),
                ('nav_color', models.CharField(default='#000000', max_length=7, validators=[pages.models.layout_validator])),
                ('layout', models.CharField(choices=[('standard', 'Standard'), ('stacked', 'Stacked')], default='standard', max_length=20)),
                ('video_embed', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='page-slug')),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('leave_capture', models.BooleanField(default=True)),
            ],
        ),
    ]
