# Generated by Django 2.1.7 on 2019-05-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_system', '0002_form_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formrecipient',
            old_name='recipient_Form_id',
            new_name='recipient_form_id',
        ),
    ]
