# Generated by Django 2.1.7 on 2019-05-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_system', '0003_auto_20190508_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='tags',
        ),
        migrations.AddField(
            model_name='form',
            name='form_type',
            field=models.CharField(default='Form', max_length=128),
        ),
    ]
