# Generated by Django 2.1.7 on 2019-02-20 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='corroborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corroboratorAuthorName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='others_involved',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
