# Generated by Django 2.1.7 on 2019-05-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0002_auto_20190508_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(default='Report', max_length=256),
        ),
    ]
