# Generated by Django 2.1.7 on 2019-03-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0004_auto_20190318_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='notes',
        ),
    ]
