# Generated by Django 2.1.7 on 2019-03-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0005_remove_ticket_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuschange',
            name='status',
            field=models.CharField(default='Open', max_length=10),
        ),
    ]
