# Generated by Django 2.1.7 on 2019-04-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0007_ticket_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='others_involved',
            field=models.TextField(blank=True, null=True),
        ),
    ]
