# Generated by Django 2.1.7 on 2019-05-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0008_auto_20190410_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='corroborator',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='offender',
        ),
        migrations.AddField(
            model_name='ticket',
            name='corroborators',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='offenders',
            field=models.TextField(blank=True, null=True),
        ),
    ]
