# Generated by Django 2.1.7 on 2019-05-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0009_auto_20190501_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
