# Generated by Django 2.1.4 on 2018-12-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='parent_message_id',
        ),
        migrations.AddField(
            model_name='message',
            name='group_message_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='groupMessage', to='message_system.UserGroup'),
            preserve_default=False,
        ),
    ]
