# Generated by Django 2.1.2 on 2018-12-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(max_length=280),
        ),
    ]
