# Generated by Django 2.1.2 on 2019-01-19 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerecipient',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messageRecipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='recipient_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messageGroup', to='message_system.UserGroup'),
        ),
    ]
