# Generated by Django 2.1.4 on 2019-01-28 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_system', '0002_auto_20190127_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='group_message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupMessage', to='message_system.UserGroup'),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='message_system.Message'),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messageRecipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='recipient_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messageGroup', to='message_system.UserGroup'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupAuthorName', to=settings.AUTH_USER_MODEL),
        ),
    ]
