# Generated by Django 2.1.2 on 2019-01-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_system', '0003_auto_20190128_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
