# Generated by Django 2.1.7 on 2019-05-08 23:05

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile_image', models.TextField(blank=True)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[user.models.MyValidator()], verbose_name='username')),
                ('bio', models.TextField(blank=True, null=True)),
                ('opt_in', models.BooleanField(blank=True, default=False)),
                ('lfg', models.BooleanField(blank=True, default=False)),
                ('discord_url', models.CharField(blank=True, max_length=250)),
                ('twitter_url', models.CharField(blank=True, max_length=250)),
                ('twitch_url', models.CharField(blank=True, max_length=250)),
                ('youtube_url', models.CharField(blank=True, max_length=250)),
                ('experience_points', models.IntegerField(default=0)),
                ('guild_points', models.IntegerField(default=0)),
                ('is_leader', models.BooleanField(default=False)),
                ('is_advisor', models.BooleanField(default=False)),
                ('is_council', models.BooleanField(default=False)),
                ('is_general_officer', models.BooleanField(default=False)),
                ('is_officer', models.BooleanField(default=False)),
                ('is_senior_member', models.BooleanField(default=False)),
                ('is_junior_member', models.BooleanField(default=False)),
                ('is_recruit', models.BooleanField(default=False)),
                ('is_raid_leader', models.BooleanField(default=False)),
                ('is_banker', models.BooleanField(default=False)),
                ('is_recruiter', models.BooleanField(default=False)),
                ('is_class_lead', models.BooleanField(default=False)),
                ('is_crafter_lead', models.BooleanField(default=False)),
                ('is_host', models.BooleanField(default=False)),
                ('is_lore_master', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('-username',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('race', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('character_class', models.CharField(blank=True, max_length=20, null=True)),
                ('profession', models.CharField(blank=True, max_length=20)),
                ('profession_specialization', models.CharField(blank=True, max_length=20)),
                ('main', models.BooleanField(default=False)),
                ('alt', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characterAuthorName', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ('-main', '-alt', '-date_created'),
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_footer', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userSettings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ('-user',),
            },
        ),
    ]
