# Generated by Django 2.1.1 on 2018-10-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='discord_url',
            new_name='discordUrl',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='primary_class',
            new_name='primaryClass',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='primary_role',
            new_name='primaryRole',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_image',
            new_name='profileImage',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='secondary_class',
            new_name='secondaryClass',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='secondary_role',
            new_name='secondaryRole',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='twitch_url',
            new_name='twitchUrl',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='twitter_url',
            new_name='twitterUrl',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='youtube_url',
            new_name='youtubeUrl',
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
