# Generated by Django 2.1.2 on 2018-12-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-username',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
