# Generated by Django 2.1.2 on 2019-02-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190205_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lfg',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
