# Generated by Django 2.1.1 on 2018-10-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181011_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='discordUrl',
            new_name='discord_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='primaryClass',
            new_name='primary_class',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='primaryRole',
            new_name='primary_role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profileImage',
            new_name='profile_image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='secondaryClass',
            new_name='secondary_class',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='secondaryRole',
            new_name='secondary_role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='twitchUrl',
            new_name='twitch_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='twitterUrl',
            new_name='twitter_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='youtubeUrl',
            new_name='youtube_url',
        ),
    ]
