# Generated by Django 2.1.7 on 2019-02-12 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_lfg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('level', models.PositiveIntegerField(blank=True, null=True)),
                ('race', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('character_class', models.CharField(blank=True, max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characterAuthorName', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ('-name',),
            },
        ),
    ]
