# Generated by Django 2.1.2 on 2018-11-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181113_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
