# Generated by Django 2.1.4 on 2018-12-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_advisor',
            field=models.BooleanField(default=False),
        ),
    ]
