# Generated by Django 2.1.2 on 2018-12-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_is_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_galleries',
            field=models.BooleanField(default=False),
        ),
    ]
