# Generated by Django 2.1.1 on 2018-10-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_profession_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guild_points',
            field=models.IntegerField(default=0),
        ),
    ]
