# Generated by Django 2.1.7 on 2019-02-17 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190212_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ('-date_created',), 'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_race',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession_specialization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secondary_class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secondary_race',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secondary_role',
        ),
        migrations.AddField(
            model_name='character',
            name='alt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='character',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='profession',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='profession_specialization',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
