# Generated by Django 2.1.1 on 2018-10-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_guild_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guild_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
