# Generated by Django 2.1.7 on 2019-02-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190216_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ('-main', '-alt', '-date_created'), 'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
    ]
