# Generated by Django 2.1.1 on 2018-10-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181015_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='guild_points',
            new_name='experience_points',
        ),
    ]
