# Generated by Django 2.1.1 on 2018-10-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20181015_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='race',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
