# Generated by Django 2.1.1 on 2018-10-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_race'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='race',
            new_name='primary_race',
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_race',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
