# Generated by Django 2.1.7 on 2019-03-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190301_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_lore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_references',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
