# Generated by Django 2.1.7 on 2019-03-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190316_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lore_master',
            field=models.BooleanField(default=False),
        ),
    ]
