# Generated by Django 2.1.7 on 2019-04-07 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_is_lore_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_create_article',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_create_calendar_event',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_create_galleries',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_create_lore',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_create_newsletter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_create_references',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_delete_article',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_delete_calendar_event',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_delete_newsletter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_read_article',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_read_calendar_event',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_read_newsletter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_update_article',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_update_calendar_event',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_update_newsletter',
        ),
    ]
