# Generated by Django 2.1.7 on 2019-05-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190406_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='show_footer',
            field=models.BooleanField(default=True),
        ),
    ]
