# Generated by Django 2.1.1 on 2018-10-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20181025_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='images/profiles/default.png', upload_to='images/profiles'),
        ),
    ]
