# Generated by Django 2.1.1 on 2018-11-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20181030_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_article',
            new_name='can_create_article',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='create_calendar_event',
            new_name='can_create_calendar_event',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='create_newsletter',
            new_name='can_create_newsletter',
        ),
    ]
