# Generated by Django 2.1.2 on 2019-01-25 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, max_length=280, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PollResponseAuthorName', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pollchoice',
            name='response',
        ),
        migrations.AddField(
            model_name='pollresponse',
            name='choice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PollResponse', to='poll_system.PollChoice'),
        ),
    ]
