# Generated by Django 2.1.2 on 2019-01-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0002_pollquestion_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresponse',
            name='response',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
