# Generated by Django 2.1.2 on 2019-01-26 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0002_auto_20190125_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresponse',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PollResponseAuthorName', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
