# Generated by Django 2.1.2 on 2019-01-26 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll_system', '0003_auto_20190125_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-last_modified',), 'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
        migrations.AlterModelOptions(
            name='pollresponse',
            options={'ordering': ('-last_modified',), 'verbose_name': 'Response', 'verbose_name_plural': 'Responses'},
        ),
        migrations.AlterField(
            model_name='pollresponse',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PollResponseAuthorName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pollresponse',
            unique_together={('author', 'choice_id')},
        ),
    ]
