# Generated by Django 2.1.2 on 2019-01-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0004_auto_20190125_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollchoice',
            options={'ordering': ('id',), 'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='pollquestion',
            options={'ordering': ('last_modified',), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='pollrecipient',
            options={'ordering': ('id',), 'verbose_name': 'Recipient', 'verbose_name_plural': 'Recipients'},
        ),
        migrations.AlterModelOptions(
            name='pollresponse',
            options={'ordering': ('id',), 'verbose_name': 'Response', 'verbose_name_plural': 'Responses'},
        ),
        migrations.AlterField(
            model_name='pollchoice',
            name='title',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
