# Generated by Django 2.1.4 on 2019-01-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0006_auto_20190127_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollchoice',
            options={'ordering': ('id',), 'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='pollquestion',
            options={'ordering': ('id',), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
