# Generated by Django 2.1.2 on 2019-01-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0007_auto_20190127_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollchoice',
            options={'ordering': ('question_id',), 'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
    ]
