# Generated by Django 2.1.2 on 2019-01-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0009_auto_20190129_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollchoice',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
