# Generated by Django 2.1.2 on 2019-01-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0010_auto_20190131_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoice',
            name='position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
