# Generated by Django 2.1.2 on 2019-01-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0011_auto_20190131_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollchoice',
            options={'ordering': ('question_id', 'position'), 'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='pollquestion',
            options={'ordering': ('position',), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
