# Generated by Django 2.1.2 on 2019-01-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0012_auto_20190131_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
