# Generated by Django 2.1.2 on 2019-02-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0013_poll_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
