# Generated by Django 2.1.2 on 2019-02-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0014_auto_20190131_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
