# Generated by Django 2.1.2 on 2019-02-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0015_auto_20190131_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='question',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
