# Generated by Django 2.1.7 on 2019-04-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0016_auto_20190131_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
