# Generated by Django 2.1.7 on 2019-04-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0017_pollquestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
