# Generated by Django 2.1.7 on 2019-05-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0019_auto_20190418_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_private',
        ),
    ]
