# Generated by Django 2.1.7 on 2019-05-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_system', '0020_remove_poll_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
