# Generated by Django 2.1.7 on 2019-05-08 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=250)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(default='Event', max_length=128)),
                ('min_level', models.PositiveIntegerField(blank=True, null=True)),
                ('max_level', models.PositiveIntegerField(blank=True, null=True)),
                ('locations', models.CharField(blank=True, max_length=256, null=True)),
                ('group_size', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventAuthorName', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventModifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventGroup', to='guild_calendar.Event')),
            ],
            options={
                'verbose_name': 'EventGroup',
                'verbose_name_plural': 'EventGroups',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='EventGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('role_class_preferences', models.TextField(default='Any')),
                ('event_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventGroupMember', to='guild_calendar.EventGroup')),
                ('filled', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventGroupMemberAuthorName', to='user.Character')),
            ],
            options={
                'verbose_name': 'EventGroupMember',
                'verbose_name_plural': 'EventGroupMembers',
                'ordering': ('position',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventgroupmember',
            unique_together={('filled', 'event_group_id')},
        ),
    ]
