# Generated by Django 2.1.4 on 2019-02-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild_calendar', '0002_auto_20190205_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='congregation_size',
            new_name='party_size',
        ),
    ]
