# Generated by Django 2.1.7 on 2019-05-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_calendar', '0002_auto_20190508_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sub_tags',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
