# Generated by Django 2.1.7 on 2019-05-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_calendar', '0003_event_sub_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='locations',
            field=models.CharField(blank=True, default='Locations', max_length=256, null=True),
        ),
    ]
