# Generated by Django 2.1.4 on 2019-02-08 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild_calendar', '0003_auto_20190208_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_preferences', models.CharField(blank=True, max_length=512, null=True)),
                ('class_preferences', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'EventGroup',
                'verbose_name_plural': 'EventGroups',
                'ordering': ('event_id',),
            },
        ),
        migrations.RenameField(
            model_name='event',
            old_name='party_size',
            new_name='group_size',
        ),
        migrations.RemoveField(
            model_name='event',
            name='class_preferences',
        ),
        migrations.RemoveField(
            model_name='event',
            name='role_preferences',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventGroup', to='guild_calendar.Event'),
        ),
    ]
