# Generated by Django 2.1.4 on 2019-02-08 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild_calendar', '0004_auto_20190208_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_preferences', models.CharField(blank=True, max_length=512, null=True)),
                ('class_preferences', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventgroup',
            name='class_preferences',
        ),
        migrations.RemoveField(
            model_name='eventgroup',
            name='role_preferences',
        ),
        migrations.AddField(
            model_name='eventgroupmember',
            name='event_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventGroup', to='guild_calendar.EventGroup'),
        ),
    ]
