# Generated by Django 2.1.7 on 2019-05-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_calendar', '0004_auto_20190514_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_level',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
