# Generated by Django 2.1.7 on 2019-05-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_calendar', '0005_auto_20190514_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sub_tags',
            field=models.CharField(blank=True, default=1, max_length=512),
            preserve_default=False,
        ),
    ]
