# Generated by Django 2.1.4 on 2019-02-08 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild_calendar', '0005_auto_20190208_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventgroupmember',
            options={'ordering': ('event_group_id',), 'verbose_name': 'EventGroupMember', 'verbose_name_plural': 'EventGroupMembers'},
        ),
        migrations.AlterField(
            model_name='eventgroupmember',
            name='event_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventGroupMember', to='guild_calendar.EventGroup'),
        ),
    ]
