# Generated by Django 2.1.4 on 2019-02-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_calendar', '0006_auto_20190208_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventgroup',
            options={'ordering': ('position',), 'verbose_name': 'EventGroup', 'verbose_name_plural': 'EventGroups'},
        ),
        migrations.AlterModelOptions(
            name='eventgroupmember',
            options={'ordering': ('position',), 'verbose_name': 'EventGroupMember', 'verbose_name_plural': 'EventGroupMembers'},
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='position',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventgroupmember',
            name='position',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
