# Generated by Django 2.1.4 on 2019-02-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_calendar', '0008_auto_20190210_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='group_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
