# Generated by Django 2.1.7 on 2019-02-14 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guild_calendar', '0011_auto_20190211_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroupmember',
            name='filled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventGroupMemberAuthorName', to=settings.AUTH_USER_MODEL),
        ),
    ]
