# Generated by Django 2.1.7 on 2019-02-16 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190212_1607'),
        ('guild_calendar', '0014_event_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventgroupmember',
            unique_together={('filled', 'event_group_id')},
        ),
    ]
