# Generated by Django 2.1.7 on 2019-02-19 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild_calendar', '0018_auto_20190215_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroupmember',
            name='filled',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='eventGroupMemberAuthorName', to='user.Character'),
        ),
    ]
