# Generated by Django 2.1.7 on 2019-02-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_calendar', '0022_auto_20190218_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroupmember',
            name='role_class_preferences',
            field=models.TextField(default='Any'),
        ),
    ]
