# Generated by Django 2.1.7 on 2019-03-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_calendar', '0023_auto_20190218_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
